### ISSUE TITLE
Refresh on context change?

### ISSUE THREAD

**Issue by pimvdnoll** [mendix/HTMLSnippet#11]
When does this one triggered? I have a situation where I validate some form input and flip a boolean if the whole form is valid or not. This will show a message and triggers a javascript (for testing now a messagebox). The first validation everything goes well and shows a messagebox. Second attempt validation when there is still not a valid form it does not trigger the javascript in the widget. I refresh the object where the widget is used..

any hints?

**Comment by pimvdnoll** [comment]
Hey Jelte! any clue about this issue?

**Comment by pimvdnoll** [comment]
Any updates maybe?

**Comment by JelteMX** [comment]
@pimvdnoll I have checked the code and it is kind of strange that this option is even there:
Refresh on context change:

- True: Update the widget (run the snippet) when an update is called. This update is only when the context object is changed (which means that it should trigger when the dataview receives a context object or when it is changed)
- False: Update the widget only when you create the widget. So this is only called when you initialise the page and not when the context object changes

In your case (if I read it correctly): It doesn't do anything with the validation on the second attempt. Your form is still not valid, so it doesn't change the context object.

If the issue is persistent and you're not able to fix it, drop me an e-mail with a small test-project that reproduces this problem, then I can check if this is a flaw in the logic of the project, or things need to be fixed in the widget

**Comment by pimvdnoll** [comment]
Hi  Jelte, thnx for the headsup, I added a cachebust in the object and after validation and solves the issue (it forces to change the context).
see: 
https://modelshare.mendix.com/models/052421f1-0618-4db9-80a9-c12efd4ead68/s-f-save-and-validate-request
